//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffeModule
    {
        public int numAff { get; set; }
        public int numFormateur { get; set; }
        public int codeM { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Formateur Formateur { get; set; }
    }
}
