//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groupe
    {
        public int codeg { get; set; }
        public string nomG { get; set; }
        public int codeFil { get; set; }
    
        public virtual Filliere Filliere { get; set; }
    }
}
