//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspweb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Projet_Fin_FormationEntities : DbContext
    {
        public Projet_Fin_FormationEntities()
            : base("name=Projet_Fin_FormationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AffeModule> AffeModules { get; set; }
        public virtual DbSet<Filliere> Fillieres { get; set; }
        public virtual DbSet<Formateur> Formateurs { get; set; }
        public virtual DbSet<Groupe> Groupes { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<salle> salles { get; set; }
        public virtual DbSet<Secteur> Secteurs { get; set; }
    }
}
